[tools]
bun = "1.3.10"

[tasks.install]
description = "Install project dependencies"
env = { PUPPETEER_SKIP_DOWNLOAD = "true" }
run = "bun install"

[tasks.login]
description = "Run the login command"
run = "bun run start -- login"

[tasks.export-as-mathcha-dir]
description = "Export as mathcha dir"
run = "bun run start -- export-as-mathcha-dir"

[tasks.print-mathcha]
description = "Print mathcha"
run = "bun run start -- print-mathcha"

[tasks.test]
description = "Run tests"
run = "bun test"